name: delivery_mvp
description: MVP Application for Delivery

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.12
  provider: ^6.0.5
  auto_route: ^7.7.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.2
  auto_route_generator: 7.1.1
  lints: ^2.1.1

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:

  uses-material-design: true
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/popins/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/colors/
